"""Graph-only comparison and distance-tree construction.

All structural evidence comes from anonymous characters generated by the
operator/layer graph. Paper labels never enter a distance calculation.
"""

from __future__ import annotations

import itertools
import math
from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Sequence

from .canonical import content_digest, freeze_json
from .computation_graph import (
    GraphDistance,
    compare_graphs,
    discover_graph_characters,
)
from .schema import ArchitecturalGenome


COMPARISON_VERSION = "3"


@dataclass(frozen=True)
class ProfileComparison:
    """Auditable pairwise comparison in anonymous graph-character space."""

    left_id: str
    right_id: str
    left_digest: str
    right_digest: str
    graph_distance: GraphDistance
    shared_characters: Mapping[str, int]
    left_only_characters: Mapping[str, int]
    right_only_characters: Mapping[str, int]
    comparison_version: str = COMPARISON_VERSION

    def __post_init__(self) -> None:
        if (
            not isinstance(self.left_id, str)
            or not self.left_id.strip()
            or not isinstance(self.right_id, str)
            or not self.right_id.strip()
            or self.left_id == self.right_id
        ):
            raise ValueError("a comparison requires two distinct artifact IDs")
        if not isinstance(self.graph_distance, GraphDistance):
            raise TypeError("graph_distance must be a GraphDistance")
        if (
            not isinstance(self.left_digest, str)
            or not self.left_digest
            or not isinstance(self.right_digest, str)
            or not self.right_digest
        ):
            raise ValueError("comparison endpoint digests must be non-empty strings")
        if (
            self.left_digest != self.graph_distance.left_digest
            or self.right_digest != self.graph_distance.right_digest
        ):
            raise ValueError(
                "comparison endpoint digests must match graph-distance endpoints"
            )
        if self.comparison_version != COMPARISON_VERSION:
            raise ValueError(f"comparison_version must be {COMPARISON_VERSION!r}")
        for name in (
            "shared_characters",
            "left_only_characters",
            "right_only_characters",
        ):
            raw = getattr(self, name)
            normalized: dict[str, int] = {}
            for key, value in sorted(raw.items()):
                if not isinstance(key, str) or not key.strip():
                    raise ValueError("character IDs must be non-empty strings")
                if isinstance(value, bool) or not isinstance(value, int):
                    raise TypeError("character counts must be integers")
                if value < 0:
                    raise ValueError("character counts cannot be negative")
                if value:
                    normalized[key.strip()] = value
            object.__setattr__(self, name, freeze_json(normalized))

    @property
    def distance(self) -> float:
        return self.graph_distance.distance

    @property
    def digest(self) -> str:
        return content_digest(self.to_dict(include_digest=False))

    def to_dict(self, *, include_digest: bool = True) -> dict[str, Any]:
        result: dict[str, Any] = {
            "artifact_type": "phylodigy.graph_comparison",
            "comparison_version": self.comparison_version,
            "graph_distance": self.graph_distance.to_dict(),
            "left": {"digest": self.left_digest, "id": self.left_id},
            "right": {"digest": self.right_digest, "id": self.right_id},
            "shared_characters": dict(self.shared_characters),
            "left_only_characters": dict(self.left_only_characters),
            "right_only_characters": dict(self.right_only_characters),
        }
        if include_digest:
            result["digest"] = content_digest(result)
        return result


def compare_profiles(
    left: ArchitecturalGenome,
    right: ArchitecturalGenome,
    *,
    radii: Iterable[int] = (0, 1, 2, 3),
    radius_weights: Mapping[int, float] | None = None,
    region_weight: float = 1.0,
    **removed_options: Any,
) -> ProfileComparison:
    """Compare two genomes without consulting names, papers, or a catalog."""

    if removed_options:
        names = ", ".join(sorted(removed_options))
        raise TypeError(f"unsupported non-graph comparison options: {names}")
    if not isinstance(left, ArchitecturalGenome) or not isinstance(right, ArchitecturalGenome):
        raise TypeError("compare_profiles expects ArchitecturalGenome objects")
    if left.artifact_id == right.artifact_id:
        raise ValueError("cannot compare an artifact with itself")
    selected_radii = tuple(radii)
    distance = compare_graphs(
        left.graph_profile,
        right.graph_profile,
        radii=selected_radii,
        radius_weights=radius_weights,
        region_weight=region_weight,
    )
    left_counts = selected_character_counts(left, radii=selected_radii)
    right_counts = selected_character_counts(right, radii=selected_radii)
    shared = {
        key: min(left_counts[key], right_counts[key])
        for key in sorted(set(left_counts) & set(right_counts))
        if min(left_counts[key], right_counts[key]) > 0
    }
    left_only = {
        key: left_counts[key] - right_counts.get(key, 0)
        for key in sorted(left_counts)
        if left_counts[key] > right_counts.get(key, 0)
    }
    right_only = {
        key: right_counts[key] - left_counts.get(key, 0)
        for key in sorted(right_counts)
        if right_counts[key] > left_counts.get(key, 0)
    }
    return ProfileComparison(
        left_id=left.artifact_id,
        right_id=right.artifact_id,
        left_digest=left.structural_digest,
        right_digest=right.structural_digest,
        graph_distance=distance,
        shared_characters=shared,
        left_only_characters=left_only,
        right_only_characters=right_only,
    )


def selected_character_counts(
    genome: ArchitecturalGenome,
    *,
    radii: Iterable[int] = (0, 1, 2, 3),
) -> dict[str, int]:
    """Recompute a genome's character vector for the selected analysis radii."""

    characters = discover_graph_characters(
        genome.graph_profile.graph,
        regions=genome.graph_profile.regions,
        radii=radii,
    )
    return {item.character_id: item.count for item in characters}


def pairwise_profile_comparisons(
    profiles: Iterable[ArchitecturalGenome],
    **kwargs: Any,
) -> tuple[ProfileComparison, ...]:
    """Return every unordered graph-only pair in deterministic order."""

    ordered = tuple(sorted(profiles, key=lambda item: item.artifact_id))
    ids = [item.artifact_id for item in ordered]
    if len(ids) != len(set(ids)):
        raise ValueError("artifact IDs must be unique")
    return tuple(
        compare_profiles(left, right, **kwargs)
        for left, right in itertools.combinations(ordered, 2)
    )


def distance_matrix(
    profiles: Iterable[ArchitecturalGenome],
    **kwargs: Any,
) -> dict[str, Any]:
    """Build the raw, unnormalized pairwise matrix used for phylogeny."""

    ordered = tuple(sorted(profiles, key=lambda item: item.artifact_id))
    comparisons = pairwise_profile_comparisons(ordered, **kwargs)
    values: dict[tuple[str, str], float] = {}
    for item in comparisons:
        values[(item.left_id, item.right_id)] = item.distance
        values[(item.right_id, item.left_id)] = item.distance
    ids = [item.artifact_id for item in ordered]
    return {
        "artifact_ids": ids,
        "matrix": [
            [0.0 if left == right else values[(left, right)] for right in ids]
            for left in ids
        ],
        "metric": "weighted_l1_dynamic_graph_characters",
        "normalization": "none",
    }


def _comparison_lookup(
    comparisons: Iterable[ProfileComparison],
) -> tuple[tuple[str, ...], dict[tuple[str, str], float]]:
    ids: set[str] = set()
    distances: dict[tuple[str, str], float] = {}
    pair_counts: dict[tuple[str, str], int] = {}
    endpoint_digests: dict[str, set[str]] = {}
    signatures: set[str] = set()
    schemes: set[str] = set()
    for item in comparisons:
        if not isinstance(item, ProfileComparison):
            raise TypeError("comparisons must contain ProfileComparison objects")
        if (
            item.left_digest != item.graph_distance.left_digest
            or item.right_digest != item.graph_distance.right_digest
        ):
            raise ValueError(
                "comparison endpoint digests must match graph-distance endpoints"
            )
        ids.update((item.left_id, item.right_id))
        key = tuple(sorted((item.left_id, item.right_id)))
        pair_counts[key] = pair_counts.get(key, 0) + 1
        distances[key] = item.distance
        endpoint_digests.setdefault(item.left_id, set()).add(item.left_digest)
        endpoint_digests.setdefault(item.right_id, set()).add(item.right_digest)
        signatures.add(item.graph_distance.distance_signature)
        schemes.add(item.graph_distance.scheme)
    duplicates = sorted(key for key, count in pair_counts.items() if count > 1)
    if duplicates:
        raise ValueError(f"duplicate comparison pairs: {duplicates}")
    conflicting_endpoints = sorted(
        artifact_id
        for artifact_id, digests in endpoint_digests.items()
        if len(digests) > 1
    )
    if conflicting_endpoints:
        raise ValueError(
            "artifact IDs map to conflicting structural digests: "
            + ", ".join(conflicting_endpoints)
        )
    if not distances:
        return (), {}
    if len(signatures) != 1 or "" in signatures:
        raise ValueError(
            "all pairwise distances must have one non-empty algorithm signature"
        )
    if len(schemes) != 1:
        raise ValueError("all pairwise distances must use the same scheme")
    ordered = tuple(sorted(ids))
    expected = {tuple(pair) for pair in itertools.combinations(ordered, 2)}
    missing = expected - set(distances)
    if missing:
        raise ValueError(f"comparison matrix is incomplete; missing {sorted(missing)}")
    return ordered, distances


def diagnose_tree_likeness(
    comparisons: Iterable[ProfileComparison],
    *,
    tolerance: float = 1e-9,
) -> dict[str, Any]:
    """Audit metric and four-point conditions before tree construction."""

    tolerance = _validated_tolerance(tolerance)
    ids, distances = _comparison_lookup(comparisons)

    def distance(left: str, right: str) -> float:
        return 0.0 if left == right else distances[tuple(sorted((left, right)))]

    invalid_distances: list[dict[str, Any]] = []
    for (left, right), value in sorted(distances.items()):
        reasons = []
        if not math.isfinite(value):
            reasons.append("nonfinite")
        if value < 0:
            reasons.append("negative")
        if reasons:
            invalid_distances.append(
                {"artifact_ids": [left, right], "reasons": reasons}
            )
    distances_finite = all(
        math.isfinite(value) for value in distances.values()
    )
    distances_nonnegative = all(value >= 0 for value in distances.values())
    distance_domain_valid = distances_finite and distances_nonnegative

    triangle_violations: list[dict[str, Any]] = []
    maximum_triangle_violation: float | None = 0.0
    triangle_count = math.comb(len(ids), 3) if len(ids) >= 3 else 0
    if distance_domain_valid:
        for triple in itertools.combinations(ids, 3):
            a, b, c = triple
            for left, right, via in ((a, b, c), (a, c, b), (b, c, a)):
                violation = max(
                    0.0,
                    distance(left, right)
                    - distance(left, via)
                    - distance(via, right),
                )
                maximum_triangle_violation = max(
                    float(maximum_triangle_violation), violation
                )
                if violation > tolerance:
                    triangle_violations.append(
                        {
                            "artifact_ids": list(triple),
                            "long_edge": [left, right],
                            "via": via,
                            "violation": violation,
                        }
                    )
    else:
        maximum_triangle_violation = None

    quartets = []
    violation_count = 0
    maximum: float | None = 0.0
    if distance_domain_valid:
        for quartet in itertools.combinations(ids, 4):
            a, b, c, d = quartet
            sums = sorted(
                (
                    distance(a, b) + distance(c, d),
                    distance(a, c) + distance(b, d),
                    distance(a, d) + distance(b, c),
                )
            )
            violation = max(0.0, sums[2] - sums[1])
            maximum = max(float(maximum), violation)
            if violation > tolerance:
                violation_count += 1
                quartets.append(
                    {"artifact_ids": list(quartet), "violation": violation}
                )
    else:
        maximum = None
    total = math.comb(len(ids), 4) if len(ids) >= 4 else 0
    metric_within_tolerance = (
        distance_domain_valid and not triangle_violations
    )
    return {
        "additive_within_tolerance": (
            metric_within_tolerance and violation_count == 0
        ),
        "distance_domain_valid": distance_domain_valid,
        "distance_pair_count": len(distances),
        "distances_finite": distances_finite,
        "distances_nonnegative": distances_nonnegative,
        "four_point_tolerance": tolerance,
        "invalid_distances": invalid_distances,
        "maximum_four_point_violation": maximum,
        "maximum_triangle_violation": maximum_triangle_violation,
        "metric_within_tolerance": metric_within_tolerance,
        "quartet_count": total,
        "triangle_check_count": triangle_count * 3,
        "triangle_count": triangle_count,
        "triangle_violation_count": len(triangle_violations),
        "triangle_violations": triangle_violations,
        "violation_count": violation_count,
        "violations": quartets,
    }


def build_vertical_backbone(
    profiles: Sequence[ArchitecturalGenome] | None = None,
    *,
    comparisons: Iterable[ProfileComparison] | None = None,
    tolerance: float = 1e-9,
    **comparison_options: Any,
) -> dict[str, Any]:
    """Infer an unrooted neighbor-joining tree from graph-only distances."""

    tolerance = _validated_tolerance(tolerance)
    if comparisons is None:
        if profiles is None:
            raise TypeError("profiles or comparisons are required")
        comparisons = pairwise_profile_comparisons(profiles, **comparison_options)
    items = tuple(comparisons)
    ids, pair_distances = _comparison_lookup(items)
    if len(ids) < 2:
        raise ValueError("at least two genomes are required")
    diagnostics = diagnose_tree_likeness(items, tolerance=tolerance)
    if not diagnostics["distance_domain_valid"]:
        raise ValueError("pairwise distances must be finite and non-negative")
    edges, limb_diagnostics = _neighbor_joining(
        ids, pair_distances, tolerance=tolerance
    )
    diagnostics["neighbor_joining"] = limb_diagnostics
    diagnostics["tree_metric_within_tolerance"] = bool(
        diagnostics["additive_within_tolerance"]
        and limb_diagnostics["nonnegative_within_tolerance"]
    )
    result = {
        "artifact_type": "phylodigy.architecture_phylogeny",
        "distance_model": "weighted_l1_dynamic_graph_characters",
        "edges": edges,
        "method": "neighbor_joining",
        "normalization": "none",
        "taxa": list(ids),
        "tree_likeness": diagnostics,
    }
    result["digest"] = content_digest(result)
    return result


def _neighbor_joining(
    ids: Sequence[str],
    pair_distances: Mapping[tuple[str, str], float],
    *,
    tolerance: float,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    active = list(ids)
    distances: dict[tuple[str, str], float] = {
        tuple(sorted(key)): float(value) for key, value in pair_distances.items()
    }
    edges: list[dict[str, Any]] = []
    negative_limbs: list[dict[str, Any]] = []
    raw_lengths: list[float] = []
    internal_index = 0
    used_ids = set(ids)

    def get(left: str, right: str) -> float:
        return 0.0 if left == right else distances[tuple(sorted((left, right)))]

    def internal_id() -> str:
        nonlocal internal_index
        while True:
            candidate = f"__phylodigy_internal__:{internal_index:06d}"
            internal_index += 1
            if candidate not in used_ids:
                used_ids.add(candidate)
                return candidate

    def add_limb(parent: str, child: str, raw_length: float) -> None:
        raw_lengths.append(raw_length)
        clamped = raw_length < 0.0
        edges.append(
            {
                "branch_length": max(0.0, raw_length),
                "child": child,
                "length_clamped": clamped,
                "parent": parent,
                "raw_branch_length": raw_length,
            }
        )
        if clamped:
            negative_limbs.append(
                {
                    "child": child,
                    "parent": parent,
                    "raw_branch_length": raw_length,
                }
            )

    while len(active) > 2:
        n = len(active)
        totals = {item: sum(get(item, other) for other in active if other != item) for item in active}
        left, right = min(
            itertools.combinations(sorted(active), 2),
            key=lambda pair: (
                (n - 2) * get(*pair) - totals[pair[0]] - totals[pair[1]],
                pair,
            ),
        )
        parent = internal_id()
        delta = (totals[left] - totals[right]) / (n - 2)
        left_length = 0.5 * (get(left, right) + delta)
        right_length = get(left, right) - left_length
        for child, raw_length in ((left, left_length), (right, right_length)):
            add_limb(parent, child, raw_length)
        remaining = [item for item in active if item not in {left, right}]
        for other in remaining:
            distances[tuple(sorted((parent, other)))] = 0.5 * (
                get(left, other) + get(right, other) - get(left, right)
            )
        active = sorted(remaining + [parent])
    left, right = active
    final_parent = internal_id()
    length = 0.5 * get(left, right)
    add_limb(final_parent, left, length)
    add_limb(final_parent, right, length)
    material_negative = [
        item
        for item in negative_limbs
        if item["raw_branch_length"] < -tolerance
    ]
    diagnostics = {
        "limb_count": len(raw_lengths),
        "minimum_raw_branch_length": min(raw_lengths),
        "negative_limb_count": len(negative_limbs),
        "negative_limbs": sorted(
            negative_limbs, key=lambda item: (item["parent"], item["child"])
        ),
        "negative_limb_count_beyond_tolerance": len(material_negative),
        "nonnegative": not negative_limbs,
        "nonnegative_within_tolerance": not material_negative,
    }
    return (
        sorted(edges, key=lambda item: (item["parent"], item["child"])),
        diagnostics,
    )


def _validated_tolerance(value: float) -> float:
    if isinstance(value, bool):
        raise ValueError("tolerance must be finite and non-negative")
    try:
        result = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError("tolerance must be finite and non-negative") from exc
    if not math.isfinite(result) or result < 0:
        raise ValueError("tolerance must be finite and non-negative")
    return result


__all__ = [
    "COMPARISON_VERSION",
    "ProfileComparison",
    "build_vertical_backbone",
    "compare_profiles",
    "diagnose_tree_likeness",
    "distance_matrix",
    "pairwise_profile_comparisons",
    "selected_character_counts",
]
